# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=50)),
                ('fk_promotion_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('fk_student_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPromotionFk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_subjectpromotionfk_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Promotion')),
                ('fk_subjectpromotionfk_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='fk_professor_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Subject'),
        ),
        migrations.AddField(
            model_name='classe',
            name='fk_classe_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.Subject'),
        ),
    ]
